[package]
name = 'loc'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'loc'

[profile.release]
lto = true
codegen-units= 1

[dependencies]
extendr-api = "0.7.0"
tokei = "12.1.2"
