# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib loc, .registration = TRUE
NULL

internal_count_loc <- function(paths, excluded, include_hidden, languages) .Call(wrap__internal_count_loc, paths, excluded, include_hidden, languages)

# nolint end
