# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_loc_wrappers", use_symbols = TRUE, package_name = "loc")

#' @docType package
#' @usage NULL
#' @useDynLib loc, .registration = TRUE
NULL

internal_count_loc <- function(paths, excluded, include_hidden, languages) .Call(wrap__internal_count_loc, paths, excluded, include_hidden, languages)


# nolint end
